---
- name: Setup Hyprland dotfiles with symbolic link
  hosts: localhost
  connection: local
  gather_facts: true
  become: false

  roles:
    - { role: hyprlink, tags: [hyprlink] }
    - { role: kitty, tags: [kitty] }
