---
- name: Setup Hyprland dotfiles with symbolic link
  hosts: localhost
  connection: local
  gather_facts: true
  become: false

  roles:
    - { role: hyprlink, tags: [hyprlink] }
    - { role: kitty, tags: [kitty] }
    - { role: keyd, tags: [keyd] }
    - { role: mouseless, tags: [mouseless] }
    - { role: wl-kbptr, tags: [wl-kbptr] }
    - { role: lazyvim, tags: [lazyvim] }
