[ids]
*

[main]
# Hold Left Control to activate the 'Ctrl_Nav' layer
capslock = layer(Ctrl_Nav) 

[Ctrl_Nav:C]
# When this layer is active (i.e., when Ctrl is held):
# 1. Any key NOT listed here (like A, S, Q, or Alt) defaults to C + [that key]
#    This preserves Ctrl + Alt + P, Ctrl + Shift + P, Ctrl + C, etc.
# 2. Keys listed here override that default:
n = down
p = up
h = left
j = down
k = up
l = right
